return {
  "typescript-language-server",
  "css-lsp",
  "html-lsp",
  "json-lsp",
  "lua-language-server",
  "stylua",
  "shellcheck",
  "shfmt",
  "bash-debug-adapter",
  "bash-language-server",
  "gradle-language-server",
  "groovy-language-server",
  "java-debug-adapter",
  "java-test",
  "jdtls",
  "js-debug-adapter",
  "vim-language-server",
  "remark-language-server",
  "prettier",
  "stylua",
  "shfmt",
}

